import type { EnemyConfig } from '../types';

export const ENEMY_CONFIGS: Record<string, EnemyConfig> = {
  slime: {
    id: 'slime',
    name: '史莱姆',
    hp: 30,
    speed: 1.5,
    armor: 0,
    magicResist: 0,
    reward: 5,
    flying: false,
    color: '#7cb342',
    radius: 6,
  },
  wolf: {
    id: 'wolf',
    name: '狼',
    hp: 45,
    speed: 3.0,
    armor: 0,
    magicResist: 0,
    reward: 8,
    flying: false,
    color: '#8d6e63',
    radius: 6,
  },
  orc: {
    id: 'orc',
    name: '兽人',
    hp: 120,
    speed: 1.2,
    armor: 5,
    magicResist: 0,
    reward: 15,
    flying: false,
    color: '#558b2f',
    radius: 8,
  },
  flyer: {
    id: 'flyer',
    name: '飞行者',
    hp: 60,
    speed: 2.0,
    armor: 0,
    magicResist: 0,
    reward: 10,
    flying: true,
    color: '#29b6f6',
    radius: 5,
  },
  shielder: {
    id: 'shielder',
    name: '盾兵',
    hp: 200,
    speed: 1.0,
    armor: 15,
    magicResist: 0,
    reward: 25,
    flying: false,
    color: '#78909c',
    radius: 8,
  },
  boss: {
    id: 'boss',
    name: '森林巨兽',
    hp: 1500,
    speed: 0.8,
    armor: 20,
    magicResist: 10,
    reward: 200,
    flying: false,
    color: '#d32f2f',
    radius: 12,
  },
};
