import type { TowerConfig } from '../types';

export const TOWER_CONFIGS: Record<string, TowerConfig> = {
  archer: {
    id: 'archer',
    name: '箭塔',
    cost: 80,
    range: 3,
    damage: 8,
    fireRate: 1.2,
    projectileType: 'projectile',
    damageType: 'physical',
    targetFlags: ['ground'],
    color: '#8bc34a',
    upgrades: [
      { level: 2, cost: 120, damageMultiplier: 1.6, rangeBonus: 0.5, fireRateMultiplier: 1.1 },
      { level: 3, cost: 200, damageMultiplier: 2.4, rangeBonus: 1.0, fireRateMultiplier: 1.2 },
    ],
  },
  cannon: {
    id: 'cannon',
    name: '炮塔',
    cost: 150,
    range: 2.5,
    damage: 25,
    fireRate: 0.5,
    projectileType: 'aoe',
    damageType: 'physical',
    targetFlags: ['ground'],
    color: '#ff9800',
    upgrades: [
      { level: 2, cost: 220, damageMultiplier: 1.5, rangeBonus: 0.5, fireRateMultiplier: 1.1 },
      { level: 3, cost: 350, damageMultiplier: 2.2, rangeBonus: 0.5, fireRateMultiplier: 1.2 },
    ],
  },
  ice: {
    id: 'ice',
    name: '冰塔',
    cost: 120,
    range: 3,
    damage: 4,
    fireRate: 0.8,
    projectileType: 'projectile',
    damageType: 'ice',
    targetFlags: ['ground'],
    color: '#00bcd4',
    upgrades: [
      { level: 2, cost: 180, damageMultiplier: 1.5, rangeBonus: 0.5, fireRateMultiplier: 1.1 },
      { level: 3, cost: 280, damageMultiplier: 2.0, rangeBonus: 1.0, fireRateMultiplier: 1.2 },
    ],
  },
  lightning: {
    id: 'lightning',
    name: '雷塔',
    cost: 180,
    range: 3.5,
    damage: 15,
    fireRate: 0.7,
    projectileType: 'hitscan',
    damageType: 'lightning',
    targetFlags: ['ground', 'flying'],
    color: '#9c27b0',
    upgrades: [
      { level: 2, cost: 260, damageMultiplier: 1.6, rangeBonus: 0.5, fireRateMultiplier: 1.1 },
      { level: 3, cost: 400, damageMultiplier: 2.3, rangeBonus: 0.5, fireRateMultiplier: 1.2 },
    ],
  },
  support: {
    id: 'support',
    name: '增益塔',
    cost: 160,
    range: 4,
    damage: 0,
    fireRate: 0,
    projectileType: 'projectile',
    damageType: 'true',
    targetFlags: [],
    color: '#ffeb3b',
    upgrades: [
      { level: 2, cost: 240, damageMultiplier: 1, rangeBonus: 1, fireRateMultiplier: 1 },
      { level: 3, cost: 380, damageMultiplier: 1, rangeBonus: 1.5, fireRateMultiplier: 1 },
    ],
  },
  barracks: {
    id: 'barracks',
    name: '兵营',
    cost: 200,
    range: 3,
    damage: 30,
    fireRate: 0.4,
    projectileType: 'projectile',
    damageType: 'physical',
    targetFlags: ['ground'],
    color: '#795548',
    upgrades: [
      { level: 2, cost: 300, damageMultiplier: 1.5, rangeBonus: 0.5, fireRateMultiplier: 1.1 },
      { level: 3, cost: 480, damageMultiplier: 2.2, rangeBonus: 1, fireRateMultiplier: 1.2 },
    ],
  },
};
